# ---------------------------------------------------------------------------
# junk.py
# Created on: 2012-11-09 10:04:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Bobcat_Hab_merge = "Source Patches\\Bobcat_Hab_merge"
bobcat_scen1_lnk_100_img = "Bobcat\\bobcat_scen1_lnk_100.img"
bobcat_scen4_lnk_100_Priorit = "bobcat_scen4_lnk_100_Priorit"
Bob_resist_scen4_cum_curmap_img = "Bobcat\\Bob_resist_scen4_cum_curmap.img"
Bobcat_Hab_merge__4_ = "Source Patches\\Bobcat_Hab_merge"
circ_inv = "circ_inv"
RasterT_badg_li1_shp = "C:\\WORKSPACE\\RasterT_bobcat_2.shp"
Output_Feature_Class = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase.shp"
Output_Feature_Class__3_ = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase_Multi.shp"
Output_Layer = "RasterT_bobcat_2_Erase_Multi"
Output_Layer__2_ = "Bobcat_Hab_merge_Layer"
Bobcat_Hab_merge__2_ = "Bobcat_Hab_merge_Layer"
RasterT_badg_li1_Erase_Layer = "RasterT_bobcat_2_Erase_Multi"
Bobcat_Hab_merge__3_ = "Bobcat_Hab_merge_Layer"
RasterT_badg_li1_Erase_Layer__2_ = "RasterT_bobcat_2_Erase_Multi"
RasterT_bobcat_2_Erase_Multi = "RasterT_bobcat_2_Erase_Multi"
Output_Feature_Class__2_ = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase_Multi1.shp"
Output_raster = "C:\\WORKSPACE\\Extract_Bob_1"
Slice_Extrac1 = "C:\\WORKSPACE\\Slice_Extrac1"
bobcat_scen4_lnk_100_Priorit5_shp = "C:\\WORKSPACE\\bobcat_scen4_lnk_100_Priorit5.shp"
bobcat_scen4_lnk_100_Priorit2 = "bobcat_scen4_lnk_100_Priorit2"
CostDis_bobc1 = "C:\\WORKSPACE\\CostDis_bobc1"
bklnk = "\\\\CERI-SERVER\\Data\\GIS\\Projects\\Sonoran\\MorongoBasin\\WildPlannerAnalysis\\bklnk"
Output_Feature_Class__4_ = "C:\\WORKSPACE\\bobcat_scen4_lnk_100_Priorit6.shp"
Output_Layer__3_ = "bobcat_scen4_lnk_100_Priorit2"
bobcat_scen4_lnk_100_Priorit2__2_ = "bobcat_scen4_lnk_100_Priorit2"
CostPat_bobc1 = "C:\\WORKSPACE\\CostPat_bobc1"
CostDis_bobc4 = "C:\\WORKSPACE\\CostDis_bobc4"
bklnk2 = "\\\\CERI-SERVER\\Data\\GIS\\Projects\\Sonoran\\MorongoBasin\\WildPlannerAnalysis\\bklnk2"
bobcat_scen4_lnk_100_Priorit2__3_ = "bobcat_scen4_lnk_100_Priorit2"
CostPat_bobc6 = "C:\\WORKSPACE\\CostPat_bobc6"

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(bobcat_scen1_lnk_100_img, RasterT_badg_li1_shp, "NO_SIMPLIFY", "VALUE")

# Process: Erase
arcpy.Erase_analysis(RasterT_badg_li1_shp, Bobcat_Hab_merge, Output_Feature_Class, "")

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(Output_Feature_Class, Output_Feature_Class__3_)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Output_Feature_Class__3_, Output_Layer, "", "", "Shape Shape VISIBLE NONE;FID FID VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;ORIG_FID ORIG_FID VISIBLE NONE")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(Bobcat_Hab_merge, Output_Layer__2_, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;area area VISIBLE NONE;sizeclass sizeclass VISIBLE NONE;sqkm sqkm VISIBLE NONE")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Output_Layer__2_, "NEW_SELECTION", "\"GRIDCODE\" = 1")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Output_Layer, "BOUNDARY_TOUCHES", Bobcat_Hab_merge__2_, "", "NEW_SELECTION")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(Output_Layer__2_, "NEW_SELECTION", "\"GRIDCODE\" = 2")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(RasterT_badg_li1_Erase_Layer, "BOUNDARY_TOUCHES", Bobcat_Hab_merge__3_, "", "SUBSET_SELECTION")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(RasterT_badg_li1_Erase_Layer__2_, "SUBSET_SELECTION", "GRIDCODE = 1")

# Process: Copy Features
arcpy.CopyFeatures_management(RasterT_bobcat_2_Erase_Multi, Output_Feature_Class__2_, "", "0", "0", "0")

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(Bob_resist_scen4_cum_curmap_img, bobcat_scen4_lnk_100_Priorit, Output_raster)

# Process: Slice
arcpy.gp.Slice_sa(Output_raster, Slice_Extrac1, "3", "NATURAL_BREAKS", "1")

# Process: Select Layer By Attribute (6)
arcpy.SelectLayerByAttribute_management(Bobcat_Hab_merge__4_, "CLEAR_SELECTION", "")

# Process: Intersect
arcpy.Intersect_analysis("bobcat_scen4_lnk_100_Priorit #;'Source Patches\\Bobcat_Hab_merge' #", bobcat_scen4_lnk_100_Priorit5_shp, "ALL", "", "LINE")

# Process: Multipart To Singlepart (2)
arcpy.MultipartToSinglepart_management(bobcat_scen4_lnk_100_Priorit5_shp, Output_Feature_Class__4_)

# Process: Make Feature Layer (3)
arcpy.MakeFeatureLayer_management(Output_Feature_Class__4_, Output_Layer__3_, "", "", "FID FID VISIBLE NONE;FID_bobcat FID_bobcat VISIBLE NONE;Shape Shape VISIBLE NONE;Id Id VISIBLE NONE;grid_code grid_code VISIBLE NONE;ORIG_FID ORIG_FID VISIBLE NONE;CONNECTION CONNECTION VISIBLE NONE;FID_Bobc_1 FID_Bobc_1 VISIBLE NONE;ID_1 ID_1 VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;area area VISIBLE NONE;sizeclass sizeclass VISIBLE NONE;sqkm sqkm VISIBLE NONE")

# Process: Select Layer By Attribute (4)
arcpy.SelectLayerByAttribute_management(Output_Layer__3_, "NEW_SELECTION", "\"GRIDCODE\" = 1")

# Process: Cost Distance
arcpy.gp.CostDistance_sa(bobcat_scen4_lnk_100_Priorit2, circ_inv, CostDis_bobc1, "", bklnk)

# Process: Select Layer By Attribute (5)
arcpy.SelectLayerByAttribute_management(bobcat_scen4_lnk_100_Priorit2, "SWITCH_SELECTION", "")

# Process: Cost Path
arcpy.gp.CostPath_sa(bobcat_scen4_lnk_100_Priorit2__2_, CostDis_bobc1, bklnk, CostPat_bobc1, "BEST_SINGLE", "FID_bobcat")

# Process: Select Layer By Attribute (7)
arcpy.SelectLayerByAttribute_management(bobcat_scen4_lnk_100_Priorit2__2_, "SWITCH_SELECTION", "")

# Process: Cost Distance (2)
arcpy.gp.CostDistance_sa(bobcat_scen4_lnk_100_Priorit2__2_, circ_inv, CostDis_bobc4, "", bklnk2)

# Process: Cost Path (2)
arcpy.gp.CostPath_sa(bobcat_scen4_lnk_100_Priorit2__3_, CostDis_bobc4, bklnk2, CostPat_bobc6, "BEST_SINGLE", "FID_bobcat")

